version: "3.8"

services:
  onibus-express-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: onibus-express-frontend
    ports:
      - "8080:80"
    restart: unless-stopped
